### ISSUE TITLE
belief_existing_objects(O). doesn't work anymore since recent refactoring.

### ISSUE THREAD

**Issue by gaya-** [knowrob/knowrob_addons#104]
Could it be due to the "belief_state" graph not being created properly?

**Comment by daniel86** [comment]
Yes you are right. It's the fault of owl_parse, it does not allow yet to assert to specific RDF graph.
I will take care of it.

**Comment by daniel86** [comment]
Should work now

https://github.com/knowrob/knowrob/commit/6e58c80c51ab54689665cb67e44f6552490b1f53
https://github.com/knowrob/knowrob_addons/commit/8301f0dae43f827ce5b4edcfb75ea73497cd8690
