### ISSUE TITLE
knowrob_learning doesn't compile

### ISSUE THREAD

**Issue by Sanic** [knowrob/knowrob_addons#115]
Hi!

After cloning knowrob_addons, i can't compile due to the following error:
[100%] Built target gradle-knowrob_openease
[100%] Built target gradle-knowrob_plan_summary
warning: [options] bootstrap class path not set in conjunction with -source 1.7
/home/user/catkin_ws/src/knowrob_addons/knowrob_learning/knowrob_learning/src/main/java/org/knowrob/reinforcement/KitchenEnvironment.java:821: error: cannot find symbol
				gripper_cmd.setPosition(0.0);
				           ^
  symbol:   method setPosition(double)
  location: variable gripper_cmd of type Pr2GripperCommand
/home/user/catkin_ws/src/knowrob_addons/knowrob_learning/knowrob_learning/src/main/java/org/knowrob/reinforcement/KitchenEnvironment.java:822: error: cannot find symbol
				gripper_cmd.setMaxEffort(100.0);
				           ^
  symbol:   method setMaxEffort(double)
  location: variable gripper_cmd of type Pr2GripperCommand

I've installed the Pr2GripperCommand messages, but this doesn't fix the problem.

/edit: Happens on master as well as on the kinetic branch

**Comment by asilx** [comment]
Yes, I experienced the same error Jose's computer, trying to fix it. Could you CATKIN_IGNORE for the time being?

**Comment by Sanic** [comment]
CATKIN_IGNORE helps. With that i can compile the repo.

**Comment by asilx** [comment]
resolved 5cf9a3798ff9ab3ca5afc3346738cbd4bfbfde77
