### ISSUE TITLE
Weka Interface Tutorial

### ISSUE THREAD

**Issue by daniel86** [knowrob/knowrob_addons#40]
Story: code-iai/knowrob_backlog#7
Depends on: knowrob/knowrob_addons#39

- create tutorial about machine learning on knowrob.org
- use predicates that allow users to use the weka interface with episode data
- feature selection
- classification

**Comment by asilx** [comment]
examples are provided for now as comments. enhanced tutorials and examples will be done as soon as having knowrob.org credientials.
