### ISSUE TITLE
knowrob_addons does not build using catkin tools

### ISSUE THREAD

**Issue by airballking** [knowrob/knowrob_addons#66]
I tried build a fresh workspace with `knowrob` and `knowrob_addons` using `catkin_tools`. Unfortunately, it did not work. I know this is a nice-to-have feature. Still, I want to document this here. Maybe we manage to fix this in the future.

setup:
  ROS Indigo
  knowrob_addons commit: e4b91171f
  knowrob commit: 6d8c92b34

failure:

``` shell
Errors     << knowrob_sim_games:cmake /home/gbartels/ros/indigo/robohow/logs/knowrob_sim_games/build.cmake.004.log
CMake Error at /home/gbartels/ros/indigo/robohow/src/stacks/knowrob_addons/knowrob_sim_games/CMakeLists.txt:7 (catkin_rosjava_setup):
  Unknown CMake command "catkin_rosjava_setup".
```

further observations:
  workspace builds fine using `catkin_make`
  only `knowrob` built fine using `catkin_tools`

**Comment by bbferka** [comment]
Just ran in to the same issue on an up to date version of knowrob_addons (commit: 921def6591989d5adca46cb5233f1f1305a7dbba).  @andreihaidu, this looks like your package. Any reason why find_package(catkin REQUIRED rosjava_build_tools rosprolog knowrob_vis) is commented out? Putting it back in fixes the issue.

**Comment by andreihaidu** [comment]
Not sure why I commented it out. But how come it worked until now?

**Comment by munu8** [comment]
Hello,
I install the knowrob in the path /home/admin6/catkin_ws/src/stacks/knowrob,
then I want to install the knowrob_addons and knowrpb_gui.But I don't know which
location should I choose for the knowrob_addons and knowrob_gui?Now I put the
knowrob_addons and knowrob_gui inn the path /home/admin6/catkin_ws/src,and
input the commands
in the terminal:
cd /home/admin6/catkin_ws
catkin_make
But I find that the knowrob_addons and knowrob_gui are not install correctly.
Should I put the knowrob_addons and the knowrob_gui in the path /home/admin6/catkin_ws/src or /home/admin6/catkin_ws/src/stacks?In addition,should I modify the .rosinstall file or CMakeLists.txt?
Could you help me?Thanks a lot!
