### ISSUE TITLE
The problem about the installation of knowrob_addons

### ISSUE THREAD

**Issue by munu8** [knowrob/knowrob_addons#80]
Hello,
       I install the knowrob in the path /home/admin6/catkin_ws/src/stacks/knowrob, 
then I want to install the knowrob_addons and knowrpb_gui.But I don't know which 
location should I choose  for the knowrob_addons and knowrob_gui?Now I put the 
knowrob_addons and knowrob_gui inn the path /home/admin6/catkin_ws/src,and 
input the commands 
in the terminal:
       cd /home/admin6/catkin_ws
       catkin_make
But I find that the knowrob_addons and knowrob_gui are not install correctly.
       Should I put the knowrob_addons and the knowrob_gui in the path /home/admin6/catkin_ws/src or /home/admin6/catkin_ws/src/stacks?In addition,should I modify the .rosinstall file or CMakeLists.txt?
       Could you help me?Thanks a lot!

**Comment by asilx** [comment]
Could you maybe try installation guide available here: http://knowrob.org/installation/catkin ?

Best, 
Asil
