### ISSUE TITLE
Bugs on https://github.com/mpomarlan/knowrob_addons

### ISSUE THREAD

**Issue by ichumuh** [knowrob/knowrob_addons#83]
1. `get_object_transform` returns 'wheel' instead of 'http://www.knowrob.org/kb/knowrob_beliefstate#TestWheel'

2. `=(RefStr, 'http://knowrob.org/kb/knowrob_paramserver.owl#MapFrameSymbol')` in `get_object_transform` fails.

3. `replace_object_transforms('http://www.knowrob.org/kb/knowrob_beliefstate#TestWheel', ['map', 'http://www.knowrob.org/kb/knowrob_beliefstate#TestWheel', [0.5, 0, 0.8], [0, 0, 0, 1]])`
results in the following error msg:
`[ERROR]` [WallTime: 1497879005.558262] Error processing request: "Prolog query failed: PrologException: error(type_error(method_params, '.'(map, '.'(map, '.'(1.4978790055262158E9, [])))), context(/(jpl_call, 4), 'not all actual parameters are convertible to Java values or references'))"
['Traceback (most recent call last):\n', '  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 623, in _handle_request\n    response = convert_return_to_response(self.handler(request), self.response_class)\n', '  File "/home/ichumuh/thorin_ws/src/knowrob_addons/knowrob_beliefstate/src/knowrob_beliefstate/object_state_publisher.py", line 75, in test_srv_cb\n    sol = self.prolog_query(q)\n', '  File "/home/ichumuh/thorin_ws/src/knowrob_addons/knowrob_beliefstate/src/knowrob_beliefstate/object_state_publisher.py", line 102, in prolog_query\n    solutions = [x for x in query.solutions()]\n', '  File "/home/ichumuh/thorin_ws/src/knowrob/json_prolog/src/json_prolog/json_prolog.py", line 38, in solutions\n    \'Prolog query failed: %s\' % next_solution.solution)\n', 'PrologException: "Prolog query failed: PrologException: error(type_error(method_params, \'.\'(map, \'.\'(map, \'.\'(1.4978790055262158E9, [])))), context(/(jpl_call, 4), \'not all actual parameters are convertible to Java values or references\'))"\n']`

**Comment by daniel86** [comment]
invalid
