### ISSUE TITLE
KnowRob representation of nested designators

### ISSUE THREAD

**Issue by knowrob** [knowrob/knowrob_addons#9]
Implement mng_desig_get_value for nested designators

**Comment by daniel86** [comment]
mng_designator_props is now able to retrieve values of nested designators.
For example:
mng_designator_props(Designator, 'BOUNDINGBOX.DIMENSIONS-3D', Value).
Or:
mng_designator_props(Designator, ['BOUNDINGBOX', 'DIMENSIONS-3D'], Value).
